/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentationLayer;

/**
 *
 * @author alp_1
 */
public class AnalystForm extends javax.swing.JFrame {

    /**
     * Creates new form AnalystForm
     */
    public AnalystForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_CreateSurvey = new javax.swing.JButton();
        btn_analysisEmployee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chanket Analysis Software");

        btn_CreateSurvey.setText("Create Survey");
        btn_CreateSurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CreateSurveyActionPerformed(evt);
            }
        });

        btn_analysisEmployee.setText("Analysis Employees");
        btn_analysisEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analysisEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btn_CreateSurvey, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(btn_analysisEmployee)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CreateSurvey, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_analysisEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_analysisEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analysisEmployeeActionPerformed
        // TODO add your handling code here:
        AnalysisForm analysisForm = new AnalysisForm();
        analysisForm.setVisible(true);
    }//GEN-LAST:event_btn_analysisEmployeeActionPerformed

    private void btn_CreateSurveyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CreateSurveyActionPerformed
        SurveyForm surveyForm = new SurveyForm();
        surveyForm.setVisible(true);
    }//GEN-LAST:event_btn_CreateSurveyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CreateSurvey;
    private javax.swing.JButton btn_analysisEmployee;
    // End of variables declaration//GEN-END:variables
}
