/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentationLayer;

import businessLayer.EmployeeOperations;
import entityLayer.Employee;
import entityLayer.EmployeeSurvey;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author alp_1
 */
public class EmployeeForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    Employee answeringEmployee;
    EmployeeSurvey employeeSurvey;
    EmployeeOperations employeeOperations;

    public EmployeeForm(Employee answeringEmployee, EmployeeOperations employeeOperations) {
        this.answeringEmployee = answeringEmployee;
        this.employeeOperations = employeeOperations;
        employeeSurvey = this.employeeOperations.GetSurvey();
        if(employeeSurvey != null){
            
        
        initComponents();
        lbl_answeringEmployeeName.setText(answeringEmployee.employeeIdentification.firstName+" "+answeringEmployee.employeeIdentification.lastName);
        EmployeeToList();
        }
    }
    
    
    private void EmployeeToList(){
        
        DefaultListModel<Employee> listModel = new DefaultListModel<Employee>();
        List<Employee> notEvaluatedEmployees = employeeOperations.GetAllEmployees(answeringEmployee.employeeDepartment.name, employeeSurvey.ID, answeringEmployee.employeeIdentification.employeeID);
        for (Employee currentEmployee : notEvaluatedEmployees) {
            listModel.addElement(currentEmployee);
        }
        lst_Employees.setModel(listModel);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_Employees = new javax.swing.JList<>();
        btn_Evaluate = new javax.swing.JButton();
        btn_Refresh = new javax.swing.JButton();
        lbl_answeringEmployeeName = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chanket Analysis Software");

        lst_Employees.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lst_Employees.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lst_Employees.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lst_Employees.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jScrollPane1.setViewportView(lst_Employees);

        btn_Evaluate.setText("Evaluate This Employee");
        btn_Evaluate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EvaluateActionPerformed(evt);
            }
        });

        btn_Refresh.setText("Refresh!");
        btn_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Evaluate)
                    .addComponent(btn_Refresh))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Refresh)
                        .addGap(87, 87, 87)
                        .addComponent(btn_Evaluate))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        lbl_answeringEmployeeName.setText("label1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_answeringEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbl_answeringEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_answeringEmployeeName.getAccessibleContext().setAccessibleName("lbl_answeringEmployeeName");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EvaluateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EvaluateActionPerformed
        // TODO add your handling code here:
        DefaultListModel<Employee> listModel =(DefaultListModel<Employee>)lst_Employees.getModel();
        if(listModel.size()!=0){
        EvaluateForm evaluateForm = new EvaluateForm(employeeSurvey.ID, answeringEmployee, lst_Employees.getSelectedValue(), employeeOperations);
        evaluateForm.setVisible(rootPaneCheckingEnabled);
        listModel.remove(lst_Employees.getSelectedIndex());
        }
        else
            JOptionPane.showMessageDialog(this, "You didn't select a person!");
    }//GEN-LAST:event_btn_EvaluateActionPerformed

    private void btn_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshActionPerformed
        EmployeeToList();
    }//GEN-LAST:event_btn_RefreshActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Evaluate;
    private javax.swing.JButton btn_Refresh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label lbl_answeringEmployeeName;
    private java.awt.List list1;
    private javax.swing.JList<Employee> lst_Employees;
    // End of variables declaration//GEN-END:variables
}
