/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentationLayer;

import businessLayer.EmployeeOperations;
import entityLayer.Employee;
import entityLayer.SurveyQuestion;
import entityLayer.SurveyQuestionAnswer;
import java.util.List;
import java.util.Stack;

/**
 *
 * @author alp_1
 */
public class EvaluateForm extends javax.swing.JFrame {

    /**
     * Creates new form QuestionForm
     */
    
    Employee answeringEmployee;
    Employee evaluatingEmployee;
    EmployeeOperations employeeOperations;
    List<SurveyQuestion> questions;
    List<SurveyQuestionAnswer> answers;
    int surveyID;
    int currentQuestionIndex = -1;
    public EvaluateForm(int surveyID, Employee answeringEmployee, Employee evaluatingEmployee, EmployeeOperations employeeOperations) {

        this.surveyID = surveyID;
        this.employeeOperations = employeeOperations;
        this.answeringEmployee = answeringEmployee;
        this.evaluatingEmployee = evaluatingEmployee;
        answers = new Stack();
        questions = employeeOperations.GetAllQuestions(surveyID);
        
        initComponents();
        
        currentQuestionIndex = 0;
        
        GetNextQuestion();
    }
    
    public void GetNextQuestion(){

            lbl_question.setText(questions.get(currentQuestionIndex).questionText);
        
    }
    
    public boolean IsLastQuestion(){
        return currentQuestionIndex > questions.size()-2;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_question = new javax.swing.JLabel();
        cmb_evaluatePoint = new javax.swing.JComboBox<>();
        btn_Evaluate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chanket Analysis Software");

        lbl_question.setText("question");

        cmb_evaluatePoint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "⋆", "⋆⋆", "⋆⋆⋆", "⋆⋆⋆⋆", "⋆⋆⋆⋆⋆" }));

        btn_Evaluate.setText("Evaluate");
        btn_Evaluate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EvaluateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Evaluate)
                    .addComponent(cmb_evaluatePoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_question))
                .addContainerGap(522, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lbl_question)
                .addGap(99, 99, 99)
                .addComponent(cmb_evaluatePoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(btn_Evaluate)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        lbl_question.getAccessibleContext().setAccessibleName("lbl_question");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EvaluateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EvaluateActionPerformed
        // TODO add your handling code here:
        if(!IsLastQuestion()){
        SurveyQuestionAnswer currentAnswer = new SurveyQuestionAnswer();
        currentAnswer.answeringEmployeeID = answeringEmployee.employeeIdentification.employeeID;
        currentAnswer.evaluatedEmployeeID = evaluatingEmployee.employeeIdentification.employeeID;
        currentAnswer.pointValue = cmb_evaluatePoint.getSelectedIndex()+1;
        currentAnswer.questionID = questions.get(currentQuestionIndex).ID;
        answers.add(currentAnswer);
        currentQuestionIndex++;
        
        GetNextQuestion();
        }
        else{
        SurveyQuestionAnswer currentAnswer = new SurveyQuestionAnswer();
        currentAnswer.answeringEmployeeID = answeringEmployee.employeeIdentification.employeeID;
        currentAnswer.evaluatedEmployeeID = evaluatingEmployee.employeeIdentification.employeeID;
        currentAnswer.pointValue = cmb_evaluatePoint.getSelectedIndex()+1;
        currentAnswer.questionID = questions.get(currentQuestionIndex).ID;
        answers.add(currentAnswer);
        
        employeeOperations.InsertAnswers(answers);
        dispose();
        }
        
        
        
        
    }//GEN-LAST:event_btn_EvaluateActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Evaluate;
    private javax.swing.JComboBox<String> cmb_evaluatePoint;
    private javax.swing.JLabel lbl_question;
    // End of variables declaration//GEN-END:variables
}
